ALTER TYPE "AnalyticsSourcePage"
ADD VALUE IF NOT EXISTS 'NEW_IN';

ALTER TYPE "AnalyticsSourcePage"
ADD VALUE IF NOT EXISTS 'SALE';

ALTER TYPE "ClickSourcePage"
ADD VALUE IF NOT EXISTS 'NEW_IN';

ALTER TYPE "ClickSourcePage"
ADD VALUE IF NOT EXISTS 'SALE';