export const PRODUCT_TYPES = [
  "ABAYA",
  "DRESS",
  "SKIRT",
  "TOP",
  "HIJAB",
  "SETS",
  "MATERNITY",
  "KHIMAR",
  "JILBAB",
  "COATS_JACKETS",
  "HOODIE_SWEATSHIRT",
  "PANTS",
  "BLAZER",
  "T_SHIRT",
  "ACCESSORIES",
] as const;